### ISSUE TITLE
Modulating on/off instead of having it constantly on?

### ISSUE THREAD

**Issue by phenotypic** [aaqib12/NodeMcu-Esp8266-Homebridge-Switch#2]
Hey there,

Thank you so much for providing this script, it works perfectly for me! So much so that I want to expand my usage of it to control a mister system. The only complication is that instead of having the `"/LED=ON"` request causing the relay to stay on permanently, I would love it if it were possible to modulate the relay on for 3 seconds then off for 5 and to repeat this forever until it receives the `"/LED=OFF"` request. The problem is that; a) I have very little experience programming for Arduinos and b) despite this, I realise that instead of simply having `digitalWrite(ledPin, HIGH);` to be the command that is run when the script is requested to turn on, it should instead be something like: 

```
digitalWrite(ledPin, HIGH);
delay(3000);
digitalWrite(ledPin, LOW);
delay(5000);
```

But in a loop, this is where my knowledge of Arduino IDE programming reaches its limits. The two problems I am unable to overcome are:

1.  How would I loop this command for an infinite number of times?

2. How could you stop this loop and simply do `digitalWrite(ledPin, LOW);` when the `"/LED=OFF"` request is made?

I would really appreciate it if you could help me out as I have been unable to find any similar situations online and my distinct lack of Arduino programming means that I have been unable to solve this myself.

Thank you in advance for any assistance,

Kind regards,
Tom

**Comment by aaqib12** [comment]
Hi Tom,

I hope this helps

void loop() {
 digitalWrite(ledPin, HIGH);
delay(3000);
digitalWrite(ledPin, LOW);
delay(5000);
}

For more details refer : http://web.cecs.pdx.edu/~gerry/class/EAS199A/notes/06/whats_this_void_loop.pdf

Hope this helps :)

**Comment by phenotypic** [comment]
Thank you for your response!

I'll give that a shot later; only one question though, will that loop stop when the "off" get request is received? If not, would the following code work?

```
int value = LOW;
    if (request.indexOf("/LED=ON") != -1)  {
      //Sets the current state 
      value = HIGH;
      do
      {
      digitalWrite(ledPin, HIGH);
      delay(3000);
      digitalWrite(ledPin, LOW);
      delay(5000);
      value = HIGH;
    } while (value = HIGH);
    }
    if (request.indexOf("/LED=OFF") != -1)  {
      digitalWrite(ledPin, LOW);
      value = LOW;
    }
```
As you can see, this simply loops the command whilst `value` is "HIGH" and when it's set to LOW, it should stop it.

Thank you once again!

Kind regards,
Tom

**Comment by aaqib12** [comment]
According to my knowledge it should work. But I’m not 100% sure about that.

**Comment by phenotypic** [comment]
Okay, thank you for your help. I'll test both out soon and get back to you about what worked and what didn't.

**Comment by phenotypic** [comment]
Unfortunately, neither of the methods listed above were adequate solutions to the problem. However,  I was eventually able to implement this feature by myself in my [homebridge-nodemcu-relay](https://github.com/Tommrodrigues/homebridge-nodemcu-relay) project. Thanks anyway!
