### ISSUE TITLE
Connect more than 1 relay. 

### ISSUE THREAD

**Issue by Veeramk** [aaqib12/NodeMcu-Esp8266-Homebridge-Switch#3]
Hey thanks for the awesome code. Just wanted to know if it is possible to connect more than one relay. Cheers 🍻

**Comment by aaqib12** [comment]
Hello,

Yes it's possible you will have to modify the code to add more relays.

**Comment by Veeramk** [comment]
Thanks for your reply. Actually I am a bit newbie to this. Do you have any written code? And one more question can it be connected remotely

**Comment by aaqib12** [comment]
Hello,

I have modified the code for you go ahead and feel free to download .zip file. I haven't tested it to use it remotely but you can give it a try :) Also note that the first relay should be connected to the pin D4 and the 2nd relay should be connected to the pin D3


[Modified Code.zip](https://github.com/aaqib12/NodeMcu-Esp8266-Homebridge-Switch/files/5249217/Modified.Code.zip)

**Comment by Veeramk** [comment]
Thanks a ton. But the code is showing a error:-
Arduino: 1.8.13 (Mac OS X), Board: "NodeMCU 0.9 (ESP-12 Module), 80 MHz, Flash, Legacy (new can return nullptr), All SSL ciphers (most compatible), 4MB (FS:2MB OTA:~1019KB), v2 Lower Memory, Disabled, None, Only Sketch, 115200"

/Users/VeeramKarnawat/Downloads/Modified-2/NODEMCU_CODE/NODEMCU_CODE.ino: In function 'void loop()':
NODEMCU_CODE:74:7: error: redeclaration of 'int value'
   int value = LOW; //Relay 2
       ^
NODEMCU_CODE:64:7: error: 'int value' previously declared here
   int value = LOW; //Relay 1
       ^
exit status 1
redeclaration of 'int value'


This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

Please help 🙏🏻

**Comment by aaqib12** [comment]
I made a mistake when modifying the code. Go ahead and try now. Here is the corrected one
[Modified .zip](https://github.com/aaqib12/NodeMcu-Esp8266-Homebridge-Switch/files/5249253/Modified.zip)

**Comment by Veeramk** [comment]
Sorry for the trouble but is it possible to control fan speed?

**Comment by aaqib12** [comment]
It's possible but this code is not gonna work for that.

**Comment by Veeramk** [comment]
Its working perfectly for relay 1 but not for other relays. ☹️

**Comment by Veeramk** [comment]
found the error 
pinMode(ledPin1, OUTPUT);
  digitalWrite(ledPin1, LOW);
 
this was missing
